// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using _4_InfraData._1_Context;

#nullable disable

namespace _4_InfraData.Migrations
{
    [DbContext(typeof(CoreServiceDbContext))]
    [Migration("20260630171428_AddFinancialScopeToBalancesAndBudgets")]
    partial class AddFinancialScopeToBalancesAndBudgets
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "8.0.14")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("GroupSubCompanyDeletedDto", b =>
                {
                    b.Property<int>("CompanyId")
                        .HasColumnType("int");

                    b.Property<int>("GroupId")
                        .HasColumnType("int");

                    b.Property<string>("GroupName")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<int?>("PermissionId")
                        .HasColumnType("int");

                    b.Property<string>("PermissionName")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("SubCompanyCnpj")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("SubCompanyId")
                        .HasColumnType("int");

                    b.Property<string>("SubCompanyName")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("UserId")
                        .HasColumnType("int");

                    b.ToTable((string)null);

                    b.ToView(null, (string)null);
                });

            modelBuilder.Entity("_3_Domain._1_Entities.AccountPlanAccount", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<int?>("AccountPlanClassificationId")
                        .HasColumnType("int");

                    b.Property<int>("AccountPlanId")
                        .HasColumnType("int");

                    b.Property<string>("CostCenter")
                        .IsRequired()
                        .HasColumnType("nvarchar(450)");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("datetime2");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("Origin")
                        .HasColumnType("int");

                    b.Property<int>("Status")
                        .HasColumnType("int");

                    b.Property<DateTime?>("UpdatedAt")
                        .HasColumnType("datetime2");

                    b.HasKey("Id");

                    b.HasIndex("AccountPlanClassificationId");

                    b.HasIndex("AccountPlanId", "CostCenter")
                        .IsUnique();

                    b.ToTable("AccountPlanAccount", "dbo");
                });

            modelBuilder.Entity("_3_Domain._1_Entities.AccountPlanClassification", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<int>("AccountPlanId")
                        .HasColumnType("int");

                    b.Property<int?>("BalancoReclassificadoId")
                        .HasColumnType("int");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<int?>("TotalizerClassificationId")
                        .HasColumnType("int");

                    b.Property<int>("TypeClassification")
                        .HasColumnType("int");

                    b.Property<int>("TypeOrder")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("AccountPlanId");

                    b.HasIndex("BalancoReclassificadoId");

                    b.HasIndex("TotalizerClassificationId");

                    b.ToTable("AccountPlanClassification");
                });

            modelBuilder.Entity("_3_Domain._1_Entities.AccountPlansModel", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<int?>("CompanyId")
                        .HasColumnType("int");

                    b.Property<int>("GroupId")
                        .HasColumnType("int");

                    b.Property<int>("SourceMode")
                        .HasColumnType("int");

                    b.Property<int?>("SubCompanyId")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("CompanyId");

                    b.HasIndex("GroupId")
                        .IsUnique()
                        .HasDatabaseName("UX_AccountPlans_CanonicalGroup")
                        .HasFilter("[CompanyId] IS NULL AND [SubCompanyId] IS NULL");

                    b.HasIndex("SubCompanyId");

                    b.ToTable("AccountPlans");
                });

            modelBuilder.Entity("_3_Domain._1_Entities.BalanceteDataAccountPlanClassification", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<int>("AccountPlanClassificationId")
                        .HasColumnType("int");

                    b.Property<string>("CostCenter")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.HasIndex("AccountPlanClassificationId");

                    b.ToTable("BalanceteDataAccountPlanClassification");
                });

            modelBuilder.Entity("_3_Domain._1_Entities.BalanceteDataModel", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<int>("BalanceteId")
                        .HasColumnType("int");

                    b.Property<bool>("BudgetedAmount")
                        .HasColumnType("bit");

                    b.Property<string>("CostCenter")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<decimal>("Credit")
                        .HasColumnType("decimal(18,2)");

                    b.Property<decimal>("Debit")
                        .HasColumnType("decimal(18,2)");

                    b.Property<decimal>("FinalValue")
                        .HasColumnType("decimal(18,2)");

                    b.Property<decimal>("InitialValue")
                        .HasColumnType("decimal(18,2)");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.HasIndex("BalanceteId");

                    b.ToTable("BalanceteData");
                });

            modelBuilder.Entity("_3_Domain._1_Entities.BalanceteImportConfig", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<int>("AccountPlanId")
                        .HasColumnType("int");

                    b.Property<int>("CostCenterCol")
                        .HasColumnType("int");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("datetime2");

                    b.Property<int>("CreditCol")
                        .HasColumnType("int");

                    b.Property<int>("DebitCol")
                        .HasColumnType("int");

                    b.Property<int>("FinalValueCol")
                        .HasColumnType("int");

                    b.Property<int>("InitialValueCol")
                        .HasColumnType("int");

                    b.Property<int>("NameCol")
                        .HasColumnType("int");

                    b.Property<int>("StartRow")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.ToTable("BalanceteImportConfig");
                });

            modelBuilder.Entity("_3_Domain._1_Entities.BalanceteModel", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<int>("AccountPlansId")
                        .HasColumnType("int");

                    b.Property<int?>("CompanyId")
                        .HasColumnType("int");

                    b.Property<DateTime>("DateCreate")
                        .HasColumnType("datetime2");

                    b.Property<int>("DateMonth")
                        .HasColumnType("int");

                    b.Property<int>("DateYear")
                        .HasColumnType("int");

                    b.Property<int?>("GroupId")
                        .HasColumnType("int");

                    b.Property<int>("Status")
                        .HasColumnType("int");

                    b.Property<int?>("SubCompanyId")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("AccountPlansId");

                    b.HasIndex("CompanyId");

                    b.HasIndex("SubCompanyId");

                    b.HasIndex("GroupId", "CompanyId", "SubCompanyId", "DateYear", "DateMonth")
                        .HasDatabaseName("IX_Balancete_FinancialScope_Period");

                    b.ToTable("Balancete");
                });

            modelBuilder.Entity("_3_Domain._1_Entities.BalancoReclassificadoModel", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<int>("AccountPlanId")
                        .HasColumnType("int");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("TypeOrder")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.ToTable("BalancoReclassificado");
                });

            modelBuilder.Entity("_3_Domain._1_Entities.BalancoReclassificadoTemplate", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("TypeOrder")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.ToTable("BalancoReclassificadoTemplate");
                });

            modelBuilder.Entity("_3_Domain._1_Entities.BudgetDataModel", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<int>("BudgetId")
                        .HasColumnType("int");

                    b.Property<bool>("BudgetedAmount")
                        .HasColumnType("bit");

                    b.Property<string>("CostCenter")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<decimal>("Credit")
                        .HasColumnType("decimal(18,2)");

                    b.Property<decimal>("Debit")
                        .HasColumnType("decimal(18,2)");

                    b.Property<decimal>("FinalValue")
                        .HasColumnType("decimal(18,2)");

                    b.Property<decimal>("InitialValue")
                        .HasColumnType("decimal(18,2)");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.HasIndex("BudgetId");

                    b.ToTable("BudgetData");
                });

            modelBuilder.Entity("_3_Domain._1_Entities.BudgetModel", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<int>("AccountPlansId")
                        .HasColumnType("int");

                    b.Property<int?>("CompanyId")
                        .HasColumnType("int");

                    b.Property<DateTime>("DateCreate")
                        .HasColumnType("datetime2");

                    b.Property<int>("DateMonth")
                        .HasColumnType("int");

                    b.Property<int>("DateYear")
                        .HasColumnType("int");

                    b.Property<int?>("GroupId")
                        .HasColumnType("int");

                    b.Property<int?>("SubCompanyId")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("AccountPlansId");

                    b.HasIndex("CompanyId");

                    b.HasIndex("SubCompanyId");

                    b.HasIndex("GroupId", "CompanyId", "SubCompanyId", "DateYear", "DateMonth")
                        .HasDatabaseName("IX_Budget_FinancialScope_Period");

                    b.ToTable("Budget");
                });

            modelBuilder.Entity("_3_Domain._1_Entities.BusinessEntity", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("Bairro")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Cep")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Cnpj")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<bool>("Deleted")
                        .HasColumnType("bit");

                    b.Property<string>("Email")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Logradouro")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Municipio")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("NomeFantasia")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Numero")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("RazaoSocial")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Telefone")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Uf")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.ToTable("BusinessEntity");
                });

            modelBuilder.Entity("_3_Domain._1_Entities.ClassificationModel", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("TotalizerClassificationTemplateId")
                        .HasColumnType("int");

                    b.Property<int>("TypeClassification")
                        .HasColumnType("int");

                    b.Property<int>("TypeOrder")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("TotalizerClassificationTemplateId");

                    b.ToTable("Classification");
                });

            modelBuilder.Entity("_3_Domain._1_Entities.CompanyModel", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<int>("BusinessEntityId")
                        .HasColumnType("int");

                    b.Property<DateTime>("DateCreate")
                        .HasColumnType("datetime2");

                    b.Property<bool>("Deleted")
                        .HasColumnType("bit");

                    b.Property<int>("GroupId")
                        .HasColumnType("int");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.HasIndex("BusinessEntityId");

                    b.HasIndex("GroupId");

                    b.ToTable("Companies");
                });

            modelBuilder.Entity("_3_Domain._1_Entities.CompanyUserModel", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<int?>("CompanyId")
                        .HasColumnType("int");

                    b.Property<int>("GroupId")
                        .HasColumnType("int");

                    b.Property<int>("PermissionId")
                        .HasColumnType("int");

                    b.Property<int?>("SubCompanyId")
                        .HasColumnType("int");

                    b.Property<int>("UserId")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("CompanyId");

                    b.HasIndex("GroupId");

                    b.HasIndex("PermissionId");

                    b.HasIndex("SubCompanyId");

                    b.HasIndex("UserId");

                    b.ToTable("CompanyUsers");
                });

            modelBuilder.Entity("_3_Domain._1_Entities.ConfigPrincipal", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.ToTable("ConfigPrincipal");
                });

            modelBuilder.Entity("_3_Domain._1_Entities.GroupModel", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<int>("BusinessEntityId")
                        .HasColumnType("int");

                    b.Property<DateTime>("DateCreate")
                        .HasColumnType("datetime2");

                    b.Property<bool>("Deleted")
                        .HasColumnType("bit");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.HasIndex("BusinessEntityId");

                    b.ToTable("Groups");
                });

            modelBuilder.Entity("_3_Domain._1_Entities.InteractionModel", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<int>("Action")
                        .HasColumnType("int");

                    b.Property<int?>("BalanceteDataId")
                        .HasColumnType("int");

                    b.Property<int>("BalanceteId")
                        .HasColumnType("int");

                    b.Property<DateTime>("DateAction")
                        .HasColumnType("datetime2");

                    b.Property<int>("UserId")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("BalanceteDataId");

                    b.HasIndex("BalanceteId");

                    b.HasIndex("UserId");

                    b.ToTable("Interaction");
                });

            modelBuilder.Entity("_3_Domain._1_Entities.InvitationToCompany", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<int?>("CompanyId")
                        .HasColumnType("int");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("datetime2");

                    b.Property<int>("GroupId")
                        .HasColumnType("int");

                    b.Property<int>("InvitedById")
                        .HasColumnType("int");

                    b.Property<int>("PermissionId")
                        .HasColumnType("int");

                    b.Property<int>("Status")
                        .HasColumnType("int");

                    b.Property<int?>("SubCompanyId")
                        .HasColumnType("int");

                    b.Property<DateTime?>("UpdatedAt")
                        .HasColumnType("datetime2");

                    b.Property<int>("UserId")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("CompanyId");

                    b.HasIndex("GroupId");

                    b.HasIndex("InvitedById");

                    b.HasIndex("PermissionId");

                    b.HasIndex("SubCompanyId");

                    b.HasIndex("UserId");

                    b.ToTable("InvitationToCompany");
                });

            modelBuilder.Entity("_3_Domain._1_Entities.ParameterModel", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<int>("AccountPlansId")
                        .HasColumnType("int");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<decimal>("ParameterValue")
                        .HasColumnType("decimal(18,2)");

                    b.Property<int>("ParameterYear")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("AccountPlansId");

                    b.ToTable("Parameter");
                });

            modelBuilder.Entity("_3_Domain._1_Entities.PermissionModel", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.ToTable("Permissions");
                });

            modelBuilder.Entity("_3_Domain._1_Entities.PlansAccountUsersModel", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<int>("AccountPlansId")
                        .HasColumnType("int");

                    b.Property<int>("BalanceteId")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("AccountPlansId");

                    b.HasIndex("BalanceteId");

                    b.ToTable("PlansAccountUsers");
                });

            modelBuilder.Entity("_3_Domain._1_Entities.SonConfig", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<int?>("ConfigPrincipalId")
                        .HasColumnType("int");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.HasIndex("ConfigPrincipalId");

                    b.ToTable("SonConfig");
                });

            modelBuilder.Entity("_3_Domain._1_Entities.SubCompanyModel", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<int>("BusinessEntityId")
                        .HasColumnType("int");

                    b.Property<int>("CompanyId")
                        .HasColumnType("int");

                    b.Property<DateTime>("DateCreate")
                        .HasColumnType("datetime2");

                    b.Property<bool>("Deleted")
                        .HasColumnType("bit");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.HasIndex("BusinessEntityId");

                    b.HasIndex("CompanyId");

                    b.ToTable("SubCompanies");
                });

            modelBuilder.Entity("_3_Domain._1_Entities.TotalizerClassificationModel", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<int>("AccountPlanId")
                        .HasColumnType("int");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("TypeOrder")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.ToTable("TotalizerClassification");
                });

            modelBuilder.Entity("_3_Domain._1_Entities.TotalizerClassificationTemplate", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("TypeOrder")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.ToTable("TotalizerClassificationTemplate");
                });

            modelBuilder.Entity("_3_Domain._1_Entities.UserModel", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("Contact")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Email")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Password")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Role")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.ToTable("Users");
                });

            modelBuilder.Entity("_3_Domain._1_Entities.ViewConfig", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<int?>("AccountPlanId")
                        .HasColumnType("int");

                    b.Property<int?>("ConfigPrincipalId")
                        .HasColumnType("int");

                    b.Property<int?>("SonConfigId")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("AccountPlanId");

                    b.HasIndex("ConfigPrincipalId");

                    b.HasIndex("SonConfigId");

                    b.ToTable("ViewConfig");
                });

            modelBuilder.Entity("_4_InfraData._6_Dto_sSQL.GroupCompanyDeletedDto", b =>
                {
                    b.Property<string>("CompanyCnpj")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("CompanyId")
                        .HasColumnType("int");

                    b.Property<string>("CompanyName")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("GroupId")
                        .HasColumnType("int");

                    b.Property<string>("GroupName")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<int?>("PermissionId")
                        .HasColumnType("int");

                    b.Property<string>("PermissionName")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<int?>("UserId")
                        .HasColumnType("int");

                    b.ToTable("GroupCompanyDeletedDto");
                });

            modelBuilder.Entity("_3_Domain._1_Entities.AccountPlanAccount", b =>
                {
                    b.HasOne("_3_Domain._1_Entities.AccountPlanClassification", "AccountPlanClassification")
                        .WithMany()
                        .HasForeignKey("AccountPlanClassificationId");

                    b.HasOne("_3_Domain._1_Entities.AccountPlansModel", "AccountPlan")
                        .WithMany()
                        .HasForeignKey("AccountPlanId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("AccountPlan");

                    b.Navigation("AccountPlanClassification");
                });

            modelBuilder.Entity("_3_Domain._1_Entities.AccountPlanClassification", b =>
                {
                    b.HasOne("_3_Domain._1_Entities.AccountPlansModel", "AccountPlan")
                        .WithMany()
                        .HasForeignKey("AccountPlanId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("_3_Domain._1_Entities.BalancoReclassificadoModel", "BalancoReclassificado")
                        .WithMany()
                        .HasForeignKey("BalancoReclassificadoId");

                    b.HasOne("_3_Domain._1_Entities.TotalizerClassificationModel", "TotalizerClassification")
                        .WithMany()
                        .HasForeignKey("TotalizerClassificationId");

                    b.Navigation("AccountPlan");

                    b.Navigation("BalancoReclassificado");

                    b.Navigation("TotalizerClassification");
                });

            modelBuilder.Entity("_3_Domain._1_Entities.AccountPlansModel", b =>
                {
                    b.HasOne("_3_Domain._1_Entities.CompanyModel", "Company")
                        .WithMany()
                        .HasForeignKey("CompanyId");

                    b.HasOne("_3_Domain._1_Entities.GroupModel", "Group")
                        .WithMany()
                        .HasForeignKey("GroupId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("_3_Domain._1_Entities.SubCompanyModel", "SubCompany")
                        .WithMany()
                        .HasForeignKey("SubCompanyId");

                    b.Navigation("Company");

                    b.Navigation("Group");

                    b.Navigation("SubCompany");
                });

            modelBuilder.Entity("_3_Domain._1_Entities.BalanceteDataAccountPlanClassification", b =>
                {
                    b.HasOne("_3_Domain._1_Entities.AccountPlanClassification", "AccountPlanClassification")
                        .WithMany()
                        .HasForeignKey("AccountPlanClassificationId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("AccountPlanClassification");
                });

            modelBuilder.Entity("_3_Domain._1_Entities.BalanceteDataModel", b =>
                {
                    b.HasOne("_3_Domain._1_Entities.BalanceteModel", "Balancete")
                        .WithMany("BalancetesData")
                        .HasForeignKey("BalanceteId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Balancete");
                });

            modelBuilder.Entity("_3_Domain._1_Entities.BalanceteModel", b =>
                {
                    b.HasOne("_3_Domain._1_Entities.AccountPlansModel", "AccountPlans")
                        .WithMany("Balancetes")
                        .HasForeignKey("AccountPlansId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("_3_Domain._1_Entities.CompanyModel", "Company")
                        .WithMany()
                        .HasForeignKey("CompanyId")
                        .OnDelete(DeleteBehavior.NoAction);

                    b.HasOne("_3_Domain._1_Entities.GroupModel", "Group")
                        .WithMany()
                        .HasForeignKey("GroupId")
                        .OnDelete(DeleteBehavior.NoAction);

                    b.HasOne("_3_Domain._1_Entities.SubCompanyModel", "SubCompany")
                        .WithMany()
                        .HasForeignKey("SubCompanyId")
                        .OnDelete(DeleteBehavior.NoAction);

                    b.Navigation("AccountPlans");

                    b.Navigation("Company");

                    b.Navigation("Group");

                    b.Navigation("SubCompany");
                });

            modelBuilder.Entity("_3_Domain._1_Entities.BudgetDataModel", b =>
                {
                    b.HasOne("_3_Domain._1_Entities.BudgetModel", "Budget")
                        .WithMany()
                        .HasForeignKey("BudgetId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Budget");
                });

            modelBuilder.Entity("_3_Domain._1_Entities.BudgetModel", b =>
                {
                    b.HasOne("_3_Domain._1_Entities.AccountPlansModel", "AccountPlans")
                        .WithMany("Budgets")
                        .HasForeignKey("AccountPlansId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("_3_Domain._1_Entities.CompanyModel", "Company")
                        .WithMany()
                        .HasForeignKey("CompanyId")
                        .OnDelete(DeleteBehavior.NoAction);

                    b.HasOne("_3_Domain._1_Entities.GroupModel", "Group")
                        .WithMany()
                        .HasForeignKey("GroupId")
                        .OnDelete(DeleteBehavior.NoAction);

                    b.HasOne("_3_Domain._1_Entities.SubCompanyModel", "SubCompany")
                        .WithMany()
                        .HasForeignKey("SubCompanyId")
                        .OnDelete(DeleteBehavior.NoAction);

                    b.Navigation("AccountPlans");

                    b.Navigation("Company");

                    b.Navigation("Group");

                    b.Navigation("SubCompany");
                });

            modelBuilder.Entity("_3_Domain._1_Entities.ClassificationModel", b =>
                {
                    b.HasOne("_3_Domain._1_Entities.TotalizerClassificationTemplate", "TotalizerClassificationTemplate")
                        .WithMany()
                        .HasForeignKey("TotalizerClassificationTemplateId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("TotalizerClassificationTemplate");
                });

            modelBuilder.Entity("_3_Domain._1_Entities.CompanyModel", b =>
                {
                    b.HasOne("_3_Domain._1_Entities.BusinessEntity", "BusinessEntity")
                        .WithMany()
                        .HasForeignKey("BusinessEntityId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("_3_Domain._1_Entities.GroupModel", "Group")
                        .WithMany("Companies")
                        .HasForeignKey("GroupId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("BusinessEntity");

                    b.Navigation("Group");
                });

            modelBuilder.Entity("_3_Domain._1_Entities.CompanyUserModel", b =>
                {
                    b.HasOne("_3_Domain._1_Entities.CompanyModel", "Company")
                        .WithMany("CompanyUsers")
                        .HasForeignKey("CompanyId");

                    b.HasOne("_3_Domain._1_Entities.GroupModel", "Group")
                        .WithMany("CompanyUsers")
                        .HasForeignKey("GroupId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("_3_Domain._1_Entities.PermissionModel", "Permission")
                        .WithMany()
                        .HasForeignKey("PermissionId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("_3_Domain._1_Entities.SubCompanyModel", "SubCompany")
                        .WithMany("CompanyUsers")
                        .HasForeignKey("SubCompanyId");

                    b.HasOne("_3_Domain._1_Entities.UserModel", "User")
                        .WithMany("CompanyUsers")
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Company");

                    b.Navigation("Group");

                    b.Navigation("Permission");

                    b.Navigation("SubCompany");

                    b.Navigation("User");
                });

            modelBuilder.Entity("_3_Domain._1_Entities.GroupModel", b =>
                {
                    b.HasOne("_3_Domain._1_Entities.BusinessEntity", "BusinessEntity")
                        .WithMany()
                        .HasForeignKey("BusinessEntityId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("BusinessEntity");
                });

            modelBuilder.Entity("_3_Domain._1_Entities.InteractionModel", b =>
                {
                    b.HasOne("_3_Domain._1_Entities.BalanceteDataModel", "BalanceteData")
                        .WithMany()
                        .HasForeignKey("BalanceteDataId");

                    b.HasOne("_3_Domain._1_Entities.BalanceteModel", "Balancete")
                        .WithMany()
                        .HasForeignKey("BalanceteId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("_3_Domain._1_Entities.UserModel", "User")
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Balancete");

                    b.Navigation("BalanceteData");

                    b.Navigation("User");
                });

            modelBuilder.Entity("_3_Domain._1_Entities.InvitationToCompany", b =>
                {
                    b.HasOne("_3_Domain._1_Entities.CompanyModel", "Company")
                        .WithMany()
                        .HasForeignKey("CompanyId");

                    b.HasOne("_3_Domain._1_Entities.GroupModel", "Group")
                        .WithMany()
                        .HasForeignKey("GroupId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("_3_Domain._1_Entities.UserModel", "InvitedBy")
                        .WithMany()
                        .HasForeignKey("InvitedById")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("_3_Domain._1_Entities.PermissionModel", "Permission")
                        .WithMany()
                        .HasForeignKey("PermissionId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("_3_Domain._1_Entities.SubCompanyModel", "SubCompany")
                        .WithMany()
                        .HasForeignKey("SubCompanyId");

                    b.HasOne("_3_Domain._1_Entities.UserModel", "User")
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Company");

                    b.Navigation("Group");

                    b.Navigation("InvitedBy");

                    b.Navigation("Permission");

                    b.Navigation("SubCompany");

                    b.Navigation("User");
                });

            modelBuilder.Entity("_3_Domain._1_Entities.ParameterModel", b =>
                {
                    b.HasOne("_3_Domain._1_Entities.AccountPlansModel", "AccountPlans")
                        .WithMany()
                        .HasForeignKey("AccountPlansId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("AccountPlans");
                });

            modelBuilder.Entity("_3_Domain._1_Entities.PlansAccountUsersModel", b =>
                {
                    b.HasOne("_3_Domain._1_Entities.AccountPlansModel", "AccountPlans")
                        .WithMany()
                        .HasForeignKey("AccountPlansId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("_3_Domain._1_Entities.BalanceteModel", "Balancete")
                        .WithMany()
                        .HasForeignKey("BalanceteId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("AccountPlans");

                    b.Navigation("Balancete");
                });

            modelBuilder.Entity("_3_Domain._1_Entities.SonConfig", b =>
                {
                    b.HasOne("_3_Domain._1_Entities.ConfigPrincipal", "ConfigPrincipal")
                        .WithMany("SonConfigs")
                        .HasForeignKey("ConfigPrincipalId");

                    b.Navigation("ConfigPrincipal");
                });

            modelBuilder.Entity("_3_Domain._1_Entities.SubCompanyModel", b =>
                {
                    b.HasOne("_3_Domain._1_Entities.BusinessEntity", "BusinessEntity")
                        .WithMany()
                        .HasForeignKey("BusinessEntityId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("_3_Domain._1_Entities.CompanyModel", "Company")
                        .WithMany("SubCompanies")
                        .HasForeignKey("CompanyId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("BusinessEntity");

                    b.Navigation("Company");
                });

            modelBuilder.Entity("_3_Domain._1_Entities.ViewConfig", b =>
                {
                    b.HasOne("_3_Domain._1_Entities.AccountPlansModel", "AccountPlan")
                        .WithMany()
                        .HasForeignKey("AccountPlanId");

                    b.HasOne("_3_Domain._1_Entities.ConfigPrincipal", "ConfigPrincipal")
                        .WithMany("ViewConfigs")
                        .HasForeignKey("ConfigPrincipalId");

                    b.HasOne("_3_Domain._1_Entities.SonConfig", "SonConfig")
                        .WithMany("ViewConfigs")
                        .HasForeignKey("SonConfigId");

                    b.Navigation("AccountPlan");

                    b.Navigation("ConfigPrincipal");

                    b.Navigation("SonConfig");
                });

            modelBuilder.Entity("_3_Domain._1_Entities.AccountPlansModel", b =>
                {
                    b.Navigation("Balancetes");

                    b.Navigation("Budgets");
                });

            modelBuilder.Entity("_3_Domain._1_Entities.BalanceteModel", b =>
                {
                    b.Navigation("BalancetesData");
                });

            modelBuilder.Entity("_3_Domain._1_Entities.CompanyModel", b =>
                {
                    b.Navigation("CompanyUsers");

                    b.Navigation("SubCompanies");
                });

            modelBuilder.Entity("_3_Domain._1_Entities.ConfigPrincipal", b =>
                {
                    b.Navigation("SonConfigs");

                    b.Navigation("ViewConfigs");
                });

            modelBuilder.Entity("_3_Domain._1_Entities.GroupModel", b =>
                {
                    b.Navigation("Companies");

                    b.Navigation("CompanyUsers");
                });

            modelBuilder.Entity("_3_Domain._1_Entities.SonConfig", b =>
                {
                    b.Navigation("ViewConfigs");
                });

            modelBuilder.Entity("_3_Domain._1_Entities.SubCompanyModel", b =>
                {
                    b.Navigation("CompanyUsers");
                });

            modelBuilder.Entity("_3_Domain._1_Entities.UserModel", b =>
                {
                    b.Navigation("CompanyUsers");
                });
#pragma warning restore 612, 618
        }
    }
}
